### ISSUE TITLE
Cannot connect to O365 web site - The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by bramdejager** [bramdejager/spcb#10]
Cannot connect to O365 web site.
The error is:

The specified module could not be found. (Exception from HRESULT: 0x8007007E)

#### This work item was migrated from CodePlex
CodePlex work item ID: '25181'
Assigned to: 'BdeJager'
Vote count: '3'

**Comment by bramdejager** [comment]
[BdeJager@12-2-2014]
Hi, other users have also discovered the same issue. Please check [this discussion item](https://spcb.codeplex.com/discussions/472409). I'll update logging in the next version to determine the root cause.

**Comment by bramdejager** [comment]
[UnknownUser@12-2-2014]

**Comment by bramdejager** [comment]
[BdeJager@27-2-2014]
Please check the new version 1.3 with extended logging. This should help with finding the root cause! Please download version 1.3 and retry. 

Before retry, please set logging level to Verbose (Options » Logging level » Verbose).

**Comment by bramdejager** [comment]
[avishnyakov@27-2-2014]
Awesome news, BdeJager.
I will update  you, once I get there.

Thanks!

**Comment by bramdejager** [comment]
[UnknownUser@2-3-2014]

**Comment by bramdejager** [comment]
[TristanWatkins@4-3-2014]
Per the discussion thread linked above, try installing the SharePoint client components SDK if you're getting this error.

**Comment by bramdejager** [comment]
[avishnyakov@4-3-2014]
Probably, it would not be a great idea on highly locked and secure client's environment.
As consultant, we may work with different clients, having access to download or copy files, but not installing 3rd part stuff.

Anyway, will try, thanks for the tip.

**Comment by bramdejager** [comment]
[BdeJager@5-3-2014]
I agree and will try to figure out which assembly is causing the issue. Please check the [discussion item (same as above)](https://spcb.codeplex.com/discussions/472409) for updates. 

Regards Bram

**Comment by bramdejager** [comment]
[ndunn2000@25-6-2014]
Same problem here.  Log info below:

25-06-2014 16:11:52.051;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Information;1d32e678-2059-4f86-b1d1-54696ce50cf0;Initializing site collection (ClientContext) for https://[MYSITE].sharepoint.com/search.
25-06-2014 16:11:52.052;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Information;1d32e678-2059-4f86-b1d1-54696ce50cf0;Using SharePoint Online credentials for user 'user.name@domain.com'.
25-06-2014 16:11:52.057;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;File '' not found, check log file  for detailed information.
25-06-2014 16:11:52.058;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
25-06-2014 16:11:52.060;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.Idcrl.ManagedIdcrl.EnsureInited()
25-06-2014 16:11:52.062;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.Idcrl.ManagedIdcrl.LogonIdentity(String username, SecureString password)
25-06-2014 16:11:52.063;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.SharePointOnlineCredentials..ctor(String username, SecureString password)
25-06-2014 16:11:52.064;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at SPBrowser.SiteAuth.InitClientContext()
25-06-2014 16:11:53.640;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;The specified module could not be found. (Exception from HRESULT: 0x8007007E)
25-06-2014 16:11:53.641;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
25-06-2014 16:11:53.643;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.Idcrl.ManagedIdcrl.EnsureInited()
25-06-2014 16:11:53.644;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.Idcrl.ManagedIdcrl.LogonIdentity(String username, SecureString password)
25-06-2014 16:11:53.645;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at Microsoft.SharePoint.Client.SharePointOnlineCredentials..ctor(String username, SecureString password)
25-06-2014 16:11:53.647;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at SPBrowser.SiteAuth.InitClientContext()
25-06-2014 16:11:53.648;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at SPBrowser.SiteCollections.Add(Uri url, String username, String password, AuthN authn)
25-06-2014 16:11:53.649;PHP-L-2R6QBW1;SPCB2013.exe;1.3.1.0;General;0;Exception;1d32e678-2059-4f86-b1d1-54696ce50cf0;   at SPBrowser.AddSite.LoadSite()

**Comment by bramdejager** [comment]
[UnknownUser@25-6-2014]

**Comment by bramdejager** [comment]
[UnknownUser@12-1-2015]

**Comment by bramdejager** [comment]
[UnknownUser@17-8-2015]

**Comment by bramdejager** [comment]
**Issue closed by _BdeJager_ with comment**
Issue fixed by installing right set of assemblies (SDK), see referred discussion for more info.

**Reason closed**
Fixed
