### ISSUE TITLE
Incorrect browse to, or browse setting - when loading tenant

### ISSUE THREAD

**Issue by bramdejager** [bramdejager/spcb#35]
I notice when I load a tenant, then second click over a list 'open default browser', and also 'Browse settings page' of object, it defaults to https://name-admin.sharepoint.com, instead of name.sharepoint.com (e.g. should be RootSiteUrl in Tenant Object).
Maybe loading a site is OK, but only tested loading a tenant.
Hope this helps.
Nice tool!

#### This work item was migrated from CodePlex
CodePlex work item ID: '63994'
Vote count: '2'

**Comment by bramdejager** [comment]
[BdeJager@31-8-2015]
Could you provide additional information, please check [Report a Bug](http://spcb.codeplex.com/wikipage?title=Report%20a%20bug&referringTitle=Documentation)

**Comment by bramdejager** [comment]
[lennertc@24-7-2017]
public static string GetFolderUrl(this SPClient.Folder folder) in FolderExtentions.cs:12 uses __Folder.Context.Url__. 

When browsing via Tenant -> Site Collections -> Some Sitecollection -> Lists -> Documents:
__Folder.Context.Url__ returns the url of the __tenant-admin site url__, not the url of the SharePoint site. 

No exception occurs, just a 404.

**Comment by bramdejager** [comment]
[UnknownUser@24-7-2017]

**Comment by bramdejager** [comment]
[lennertc@24-7-2017]
Stacktrace:
at SPBrowser.Extentions.ListExtentions.GetListUrl(List list)
   at SPBrowser.MainForm.GetOpenItemUrl()
   at SPBrowser.MainForm.browseOpenUrlToolStripMenuItem_Click(Object sender, EventArgs e)

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
