### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by bramdejager** [bramdejager/spcb#7]
Hi,

I was trying to open a power shell console from my sharepoint online site and the error is:

"the system cannot find the file specified"

the action was: "Open Power shell with CSOM" doing right mouse button over the site collection.

what's missing?

Kind regards,
Ramon

#### Attachments
[screenshot01.jpg](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=spcb&WorkItemId=24967&FileAttachmentId=6627)

#### This work item was migrated from CodePlex
CodePlex work item ID: '24967'
Assigned to: 'BdeJager'
Vote count: '1'

**Comment by bramdejager** [comment]
[BdeJager@11-12-2013]
Hi Ramon,

Please check your log files and find associated error with details in there. Could you paste the error details? 

Log files can be found in the same directory as the SPCB2013.exe file. 

Regards,
Bram

**Comment by bramdejager** [comment]
[UnknownUser@11-12-2013]

**Comment by bramdejager** [comment]
[rtorras@12-12-2013]
Sure!
It doesn't tell so much but...

Time;Machine;Process;Version;Category;EventId;Level;Correlation;Message
11-12-2013 11:29:03.864;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;916f6f5c-73cf-4403-9837-c20f1eb8d34d;The system cannot find the file specified
11-12-2013 11:29:04.025;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;916f6f5c-73cf-4403-9837-c20f1eb8d34d;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:29:04.028;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;916f6f5c-73cf-4403-9837-c20f1eb8d34d;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:29:04.029;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;916f6f5c-73cf-4403-9837-c20f1eb8d34d;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:29:04.031;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;916f6f5c-73cf-4403-9837-c20f1eb8d34d;   at SPBrowser.MainBrowser.OpenPowerShellConsole()
11-12-2013 11:29:11.958;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;52636c04-f456-4be1-a608-ab9f28964289;The system cannot find the file specified
11-12-2013 11:29:11.960;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;52636c04-f456-4be1-a608-ab9f28964289;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:29:11.963;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;52636c04-f456-4be1-a608-ab9f28964289;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:29:11.965;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;52636c04-f456-4be1-a608-ab9f28964289;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:29:11.967;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;52636c04-f456-4be1-a608-ab9f28964289;   at SPBrowser.MainBrowser.OpenPowerShellConsole()
11-12-2013 11:31:30.515;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;91976cef-4165-435c-b2ef-cdf6b33ea7bd;The system cannot find the file specified
11-12-2013 11:31:30.518;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;91976cef-4165-435c-b2ef-cdf6b33ea7bd;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:31:30.520;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;91976cef-4165-435c-b2ef-cdf6b33ea7bd;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:31:30.522;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;91976cef-4165-435c-b2ef-cdf6b33ea7bd;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:31:30.524;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;91976cef-4165-435c-b2ef-cdf6b33ea7bd;   at SPBrowser.MainBrowser.OpenPowerShellConsole()
11-12-2013 11:33:25.194;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;eedda7ec-9129-4fd0-8d38-240f917083d5;The system cannot find the file specified
11-12-2013 11:33:25.197;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;eedda7ec-9129-4fd0-8d38-240f917083d5;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:33:25.199;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;eedda7ec-9129-4fd0-8d38-240f917083d5;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:33:25.201;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;eedda7ec-9129-4fd0-8d38-240f917083d5;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:33:25.202;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;eedda7ec-9129-4fd0-8d38-240f917083d5;   at SPBrowser.MainBrowser.OpenPowerShellConsole()
11-12-2013 11:35:43.466;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;cf260d3d-2bbd-4c6f-87d6-af14939299ab;The system cannot find the file specified
11-12-2013 11:35:43.470;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;cf260d3d-2bbd-4c6f-87d6-af14939299ab;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:35:43.481;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;cf260d3d-2bbd-4c6f-87d6-af14939299ab;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:35:43.484;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;cf260d3d-2bbd-4c6f-87d6-af14939299ab;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:35:43.486;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;cf260d3d-2bbd-4c6f-87d6-af14939299ab;   at SPBrowser.MainBrowser.OpenPowerShellConsole()
11-12-2013 11:39:44.024;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;51ed4e31-f465-4636-bd38-1739c3c1677b;The system cannot find the file specified
11-12-2013 11:39:44.027;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;51ed4e31-f465-4636-bd38-1739c3c1677b;System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
11-12-2013 11:39:44.028;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;51ed4e31-f465-4636-bd38-1739c3c1677b;   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
11-12-2013 11:39:44.030;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;51ed4e31-f465-4636-bd38-1739c3c1677b;   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
11-12-2013 11:39:44.072;NYO-RTORRA;SPCB2013.exe;1.1.0.0;General;0;Exception;51ed4e31-f465-4636-bd38-1739c3c1677b;   at SPBrowser.MainBrowser.OpenPowerShellConsole()

**Comment by bramdejager** [comment]
[BdeJager@13-1-2014]
Sorry for the late reply. But I was wondering if PowerShell is installed on your machine? If so, are you able to do the following steps to execute PowerShell? 

1. Hit the Windows Key + "R"
2. Type "powershell.exe"
3. Click OK

This should start a PowerShell console, does this work?

**Comment by bramdejager** [comment]
[UnknownUser@12-1-2015]

**Comment by bramdejager** [comment]
[UnknownUser@17-8-2015]

**Comment by bramdejager** [comment]
**Issue closed by _BdeJager_ with comment**
Closing the issue, last update over 1 year ago.

**Reason closed**
Fixed
